steps:
  # Step 1: Install dependencies for the main application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'

  # Step 2: Install dependencies for Firebase Functions
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'functions'

  # Step 3: Set Firebase environment variables from secret
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$FIREBASE_CONFIG" > firebase-config.json
        export NEXT_PUBLIC_FIREBASE_API_KEY=$(node -e "console.log(JSON.parse(process.env.FIREBASE_CONFIG).apiKey)")
        export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(node -e "console.log(JSON.parse(process.env.FIREBASE_CONFIG).authDomain)")
        export NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(node -e "console.log(JSON.parse(process.env.FIREBASE_CONFIG).projectId)")
        export NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(node -e "console.log(JSON.parse(process.env.FIREBASE_CONFIG).storageBucket)")
        export NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(node -e "console.log(JSON.parse(process.env.FIREBASE_CONFIG).messagingSenderId)")
        export NEXT_PUBLIC_FIREBASE_APP_ID=$(node -e "console.log(JSON.parse(process.env.FIREBASE_CONFIG).appId)")
        npm run build
    dir: '.'
    secretEnv:
      - 'FIREBASE_CONFIG'

  # Step 4: Build Firebase Functions
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'functions'

  # Step 5: Run linting (optional - can be made required later)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'lint']
    dir: '.'

  # Step 6: Deploy to Firebase (hosting, functions, firestore rules)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['firebase', 'deploy', '--project', '${_PROJECT_ID}']
    dir: '.'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-service-account.json'

# Build timeout
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Available secrets
availableSecrets:
  secretManager:
    - versionName: projects/gutcheck-score-mvp/secrets/firebase-config/versions/latest
      env: 'FIREBASE_CONFIG'

# Substitutions (will be set in Cloud Build trigger)
substitutions:
  _PROJECT_ID: 'gutcheck-score-mvp' 