steps:
  # Step 1: Install dependencies for the main application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'

  # Step 2: Install dependencies for Firebase Functions
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'functions'

  # Step 3: Build the Next.js application with Firebase environment variables
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '.'
    env:
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAUq0hEPlGnfkj6MJC-7et_gNim-YTyTzg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=gutcheck-score-mvp.firebaseapp.com'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=gutcheck-score-mvp'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=gutcheck-score-mvp.firebasestorage.app'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=286731768309'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:286731768309:web:daa2346433cefedc1e90bc'

  # Step 4: Build Firebase Functions
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'functions'

  # Step 5: Run linting (optional - can be made required later)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'lint']
    dir: '.'

  # Step 6: Deploy to Firebase (hosting, functions, firestore rules)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['firebase', 'deploy', '--project', '${_PROJECT_ID}']
    dir: '.'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-service-account.json'

# Build timeout
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'



# Substitutions (will be set in Cloud Build trigger)
substitutions:
  _PROJECT_ID: 'gutcheck-score-mvp' 