steps:
  # Step 1: Install dependencies for the main application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'

  # Step 2: Install dependencies for Firebase Functions
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'functions'

  # Step 3: Build the Next.js application with Firebase environment variables
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build
        ls -la
        echo "Build completed, out directory contents:"
        ls -la out/
    dir: '.'
    env:
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAUq0hEPlGnfkj6MJC-7et_gNim-YTyTzg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=gutcheck-score-mvp.firebaseapp.com'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=gutcheck-score-mvp'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=gutcheck-score-mvp.firebasestorage.app'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=286731768309'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:286731768309:web:daa2346433cefedc1e90bc'
      - 'ASSESSMENT_AGENT_URL=https://us-central1-gutcheck-score-mvp.cloudfunctions.net/assessment-agent'
      - 'OPEN_ENDED_SCORING_AGENT_URL=https://us-central1-gutcheck-score-mvp.cloudfunctions.net/open-ended-scoring-agent'

  # Step 4: Build Firebase Functions
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'functions'

  # Step 5: Deploy to Firebase
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ls -la
        ls -la out/
        npx firebase-tools deploy --only hosting,functions --project ${_PROJECT_ID}
    dir: '.'

# Build timeout
timeout: '1800s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions (will be set in Cloud Build trigger)
substitutions:
  _PROJECT_ID: 'gutcheck-score-mvp'
  # DEPRECATED: Gemini API key no longer needed as we've switched to ADK agent
  # _GEMINI_API_KEY: 'AIzaSyAUq0hEPlGnfkj6MJC-7et_gNim-YTyTzg' 