steps:
  # Step 1: Install dependencies for the main application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: '.'

  # Step 2: Install dependencies for Firebase Functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'

  # Step 3: Build the Next.js application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: '.'

  # Step 4: Build Firebase Functions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'functions'

  # Step 5: Run linting (optional - can be made required later)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
    dir: '.'

  # Step 6: Deploy to Firebase (hosting, functions, firestore rules)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['firebase', 'deploy', '--project', '${PROJECT_ID}', '--token', '${_FIREBASE_TOKEN}']
    dir: '.'

# Build timeout
timeout: '20m'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions (will be set in Cloud Build trigger)
substitutions:
  _FIREBASE_TOKEN: ''  # Will be set as a secret in Cloud Build

# Available substitutions
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/firebase-token/versions/latest
      env: '_FIREBASE_TOKEN' 