steps:
  # Deploy to Cloud Functions directly (no Docker required)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - assessment-agent
      - --gen2
      - --runtime=python311
      - --region=us-central1
      - --source=.
      - --entry-point=process_assessment_http
      - --trigger-http
      - --allow-unauthenticated
      - --memory=2GB
      - --timeout=540s
      - --max-instances=10
      - --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID
      - --set-env-vars=GOOGLE_CLOUD_LOCATION=us-central1
      - --set-env-vars=ENVIRONMENT=production
      - --set-env-vars=LOG_LEVEL=INFO

options:
  logging: CLOUD_LOGGING_ONLY
