name: Deploy to Firebase and Test

on:
  push:
    branches: [ main ]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build the application
      run: npm run build
    
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: gutcheck-score-mvp
    
    - name: Wait for deployment
      run: sleep 30
    
    - name: Run BrowserStack tests against live URL
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        npm install -D browserstack-node-sdk@latest
        # Update tests to use live Firebase URL instead of localhost
        npx browserstack-node-sdk playwright test tests/visual-consistency.spec.ts 